name = "StrataCLI"
version = "0.1.0"
defaultTargets = ["StrataMainLib", "strata"]

[[require]]
name = "Strata"
git = "https://github.com/strata-org/Strata"
rev = "main"

[[require]]
name = "StrataPython"
git = "https://github.com/strata-org/Strata-Python"
rev = "main"

[[require]]
name = "StrataDDM"
git = "https://github.com/strata-org/Strata-DDM"
rev = "main"

[[lean_lib]]
name = "StrataMainLib"

[[lean_exe]]
name = "strata"
root = "StrataMain"
