name = "StrataCLI"
version = "0.1.0"
defaultTargets = ["StrataMainLib", "strata"]

[[require]]
name = "Strata"
path = ".."

[[require]]
name = "StrataPython"
path = "../StrataPython"

[[lean_lib]]
name = "StrataMainLib"

[[lean_exe]]
name = "strata"
root = "StrataMain"
